### ISSUE TITLE
Why use FAT32 and not the FAT16?

### ISSUE THREAD

**Issue by bdheeman** [yoshi314/multi-live-usb-configs#1]
You suggested formatting the USB disks using FAT32, whereas the FAT16 supported maximum volume size is 2 GB (4 GB for 64 KB clusters) and we can save a lost of wasted disk space using smaller clusters, hence why we should not use FAT16 (0xE) LBA for volume/partitions <= 2 GB?

**Comment by yoshi314** [comment]
fat32 is only used for hiren's boot cd, actually. I'm sure you can try using fat16, i'm just not 100% sure it's going to work with that particular live environment (not tested personally).

In short, fat32 is a safe fallback soluton, which is fairly good for flash storage, and one most people will feel familiar with.

If hiren's bootcd will work with fat16, i'll correct the notes with appropriate information.

**Comment by bdheeman** [comment]
I also have not tested hiren's bootcd, but I (prefer and) use FAT16 for making bootable USB images for Ubuntu, LinuxMint, Debian and GRML; which work{ed,s} flawlessly.

OTOH and IMHO the GRUB 2 is a better option for booing directly off of the ISO images copied onto a USB volume.

**Comment by yoshi314** [comment]
Afaik isoboot would not work with all iso images, and i had my share of booting problems with grub2 - certain computers simply would not boot it at all. 

Also, grub is missing some features of syslinux (or has a less stable implementation), especially when you try to boot non-linux images or chainloading another bootloader, which sometimes fails to work. (e.g. attempting to chainload isolinux/memdisk for freedos/plop bootloader/etc)

Maybe 2.00 release is more compatible, as i did the tests on fairly early grub 1.98-prereleases and gave up.
